### ISSUE TITLE
Can essentia run as a server?

### ISSUE THREAD

**Issue by joeb-git** [MTG/essentia#1275]
I am currently running essentia from the command line (streaming mode) to process large batches of files.

Is it possible to persist essentia so I dont pay performance penalty by restarting with every job? I did see the essentiaRT but it still wasnt clear. I'm not trying to parallelize it or anything just only have to invoke it once.

Thanks in advance

**Comment by dbogdanov** [comment]
We do not have this functionality; however, you can write your own server. Depending on the algorithms you are using, you can configure them once and then run computations on multiple inputs. 

However, there is not much overhead to be saved in the case of MusicExtractor or FreesoundExtractor. In these two algorithms, most initialization for the internal algorithm chains is done directly inside the `compute` method.

Are you using binary extractors or running a Python script that calls some Essentia algorithms?

**Comment by joeb-git** [comment]
Thank you kindly for the response. I'm currently using the binary extractor essentia_streaming_extractor_music

**Comment by dbogdanov** [comment]
Binary `essentia_streaming_extractor_music` have a slightly less overhead than running MusicExtractor algorithm in Python. In both cases, most of configuration of internal algorithms happens inside the `compute` method. You could modify the source code for the `essentia_streaming_extractor_music`  to make it process batches of files. However, the improvement might be insignificant due to the configuration of these internal algorithms.
