### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by nishanthcgit** [MTG/essentia#1293]
Some of the pretrained models are great. I saw that the the training scripts are [here](https://github.com/palonso/musicnn-training) - I wanted to know how long does it take to train something like EffNet-Discogs using the contrastive objective? Of course it depends on dataset size but I wanted to know if it will be possible to do on colab pro if I have my own dataset.
I wanted to try this out both to work on my data and because the existing models use TF-1.x API and I would like to use a pytorch/TF-2.x CNN with the appropriate preprocessing.
EDIT: I have around 5k-6k songs, each ~8 minutes and I will be using 15 second chunks - so positive and negative pairs will come from different sections of the same song, etc. To give an idea of how much data there is to be trained on..

**Comment by palonso** [comment]
Hi @nishanthcgit,
To give you an idea, it takes about 2 days to train the contrastive learning models on a dataset of 3.3 million tracks using 6 titan 2080 rtx GPUs.

The training scripts you mention are used to obtain the downstream classification models based on the embeddings from Effnet-Discogs. The Effnet-Discogs embedding models are trained with custom Pytorch code that we don't share because it's specific for our distributed setup and then the output models are ported to TF for inference.
If you want to train similar contrastive models on a colab, I recommend you to have a look at the [official implementation](https://github.com/google-research/google-research/tree/master/cola) of COLA.

**Comment by nishanthcgit** [comment]
Thank you very much, this is super useful!
