### ISSUE TITLE
RuntimeError: audioset-vggish-3: model/vggish/pool1/MaxPool cannot be retreived

### ISSUE THREAD

**Issue by seunggookim** [MTG/essentia#1330]
Hello,
I tried to retrieve a shallow layer activation from the pre-trained model `audioset-vggish-3.pb` with `model/vggish/pool1/MaxPool` as the output node name, and a runtime error was called:
```
Traceback (most recent call last):
  File "extract_vggish_embeddings.py", line 44, in <module>
    embeddings = model(audio)
  File "[USERPATH]/.conda/envs/essentia/lib/python3.6/site-packages/essentia/standard.py", line 123, in __call__
    return self.compute(*args)
  File "[USERPATH]/.conda/envs/essentia/lib/python3.6/site-packages/essentia/standard.py", line 104, in compute
    results = self.__compute__(*convertedArgs)
RuntimeError: In TensorflowPredictVGGish.compute: acquireForWrite: Requested number of tokens (393216) > phantom size (32768) in TensorToVectorReal::frame
```
Other nodes (`pool[2-4]/MaxPool`, `embeddings`) worked fine. Is there any way to retrieve the activation of the first MaxPool node?

**Comment by palonso** [comment]
Hi @seunggookim,
It appears that the issue you are encountering is due to the requested ouptut features being larger than the output buffer. I was able to replicate the problem in my own setup and resolved it by reducing the inference batch size (tested for a 2.7 hours input audio).

To address this issue, try configuring `TensorflowpredictVGGish` with a smaller batch size (e.g., 1):
```python
TensorflowpredictVGGish(batchSize=1, ...)
```
