### ISSUE TITLE
documentation website is down

### ISSUE THREAD

**Issue by jon-myers** [MTG/essentia#1379]

**Comment by Moinketroa** [comment]
It's back up ! 
Visit : https://essentia.upf.edu/

**Comment by jon-myers** [comment]
Great!

**Comment by dbogdanov** [comment]
This happens due to occasional failures in our university hosting infrastructure. Normally, the website is swiftly back up.

In the case it happens in the future, for (slow) access to the documentation you can temporarily use the archived website at https://web.archive.org/web/https://essentia.upf.edu/
