### ISSUE TITLE
Taglib not detected

### ISSUE THREAD

**Issue by gopalkoduri** [MTG/essentia#211]
On CentOS 6.5, I've updated taglib v1.6 to v1.9.1. The installation path is /usr/local/include. But when I run ./waf configure, it does not detect taglib. I tried to add the following line to src/wscript:

ctx.env.append_value('INCLUDES', ['/usr/local/include/taglib/'])
ctx.env.append_value('INCLUDES', ['/usr/local/include/'])

But this does not help. What should I do so that the configuration script finds taglib installed on the system?

**Comment by alastair** [comment]
You could try 

    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" ./waf configure

**Comment by gopalkoduri** [comment]
Perfect, that worked! Thanks.

**Comment by gopalkoduri** [comment]
Essentia is configured with taglib detected. However, when I import it post installation, it complains saying this:

ImportError: libtag.so.1: cannot open shared object file: No such file or directory

**Comment by alastair** [comment]
This is probably because it can't find the shared library. 
Check `ldd build/src/python/essentia.so`

It'll probably show libtag.so.1 => not found

You can set the library search path:

    LD_LIBRARY_PATH=/usr/local/lib python

and then try and import again.

To fix this permantly, look at the documentation for ldconfig: http://man7.org/linux/man-pages/man8/ldconfig.8.html

You probably want to add the line `/usr/local/lib` to the file /etc/ld.so.conf and re-run ldconfig as root.

**Comment by gopalkoduri** [comment]
Thanks, that resolves it!
