### ISSUE TITLE
PyCharm 3.4 and essentia 2.0.1

### ISSUE THREAD

**Issue by gasper321** [MTG/essentia#241]
Hi again.

I am using PyCharm to use essentia. However, it does not find anything in the packages, for instance MonoLoader. Issue was reported here http://forum.jetbrains.com/thread/PyCharm-1811

@julj Which IDE do you use? 

@dbogdanov Is there a known issue with PyCharm and essentia 2.0.1?

Thanks.

**Comment by gasper321** [comment]
Maybe i should get MonoLoader from somewhere else? In the file essentia.standard.py there is nothing.

Here is the file from the system: http://pastebin.com/pFqiBd6q

**Comment by alastair** [comment]
Modules in essentia.standard are created dynamically when you import the module. What functionality is broken for you? Just auto-completion in pycharm? My guess is that pycharm is doing static analysis to discover class names, which it doesn't find because it doesn't execute the file (line 112). If you can convince pycharm to actually import essentia.standard you might see the class names.

In #221 you say that you can't run the program, but in here you say it's just an issue with pycham. What is the problem?   Please don't add comments to unrelated issues (That issue is about C++)

**Comment by julj** [comment]
>> @julj Which IDE do you use?
I use vim.

**Comment by gasper321** [comment]
Sorry for the confusion. It is just a PyCharm issue. I managed to run the tutorial program from the console without any problems.

I'm not sure exactly about the problem within PyCharm. The autocomplete definetly does not work and that is most likely due to what you mentioned (static analysis for class names). However, if I run my application (Flask web app) despite the warning of "class not found", it crashes at line 13: http://pastebin.com/QdnSiw74

Thank you for your help and feedback and sorry again about confusion.

**Comment by alastair** [comment]
It would be helpful if you also posted the output of your program including error you were getting instead of just explaining it, it would be much easier to help you.
I've tried your code and it works fine for me (Using latest essentia master).

**Comment by gasper321** [comment]
I know, i'm sorry, it was incosistent, thats why i didnt post it yet. 

I resolved the issue by updating PyCharm to latest version (4.0.5) togheter with using essentia 2.0.1 (not latest).

Thank you very much @alastair
