### ISSUE TITLE
python essentia.standard.MonoLoader on master on ubuntu does not exist

### ISSUE THREAD

**Issue by calippo** [MTG/essentia#242]
I installed essentia (the version on master) on ubuntu 14.04. Installation was successful.
I am trying to use it with python but I can't find Loader modules.

**Comment by gasper321** [comment]
If the problem is simply that they are not found (Unresolved reference), its not really a problem. Did you try running the tutorial code? Are you using python? What error do you get when running the tutorial code from http://essentia.upf.edu/documentation/python_tutorial.html or equivalent?

Of course i presume you installed the required dependencies for Loader modules (from ffmpeg package).

**Comment by calippo** [comment]
The probl

**Comment by calippo** [comment]
I didn't notice I missed some dependencies and I could not load the module.
After that I still had some problem, but I resolved as in https://github.com/MTG/essentia/issues/237.

**Comment by ShrutiSarikaChakraborty** [comment]
I have installed essentia correctly and succesfully foowing the defined steps with the depenencies in python 3,on Ubuntu bash in Win 10.I am getting this error
No module named 'essentia.standard'...I don't understand why.The example scripts are also throwing the same error.Please help
