### ISSUE TITLE
Pitch contours start earlier for the audio recordings in mp3 format

### ISSUE THREAD

**Issue by sertansenturk** [MTG/essentia#246]
While working on the predominant melody extraction for makam musics, I have observed that the computed PredominantMelody starts earlier compared to the audio recording if the format of the audio recording is mp3. 

Among the mp3 recordings I've checked the lead is always 1024 + 128 samples using the default frameSize (2048) and the default hopSize (128) (http://essentia.upf.edu/documentation/reference/streaming_PitchContours.html). When I convert the mp3 to wav (using Audacity), there are no problems.

I am sharing the simplified code to reproduce the error along with the mp3 and wav of the same 5-second sample: https://www.dropbox.com/sh/5akoo16t8jg9pe7/AAB9cxJkSTuS_Son6wyzD58ia?dl=0 I am using essentia.__version__ 2.1-beta1 You can observe the lead from the printed variables "contours_start_times" in the code.

**Comment by dbogdanov** [comment]
The problem is more generic, the loaded mp3 audio starts earlier:
![timeshift](https://cloud.githubusercontent.com/assets/409668/7026167/7e82e008-dd48-11e4-9d48-dee2de068a63.png)
although when I open both files in Audacity, they start at the same time.

How did you create the mp3 file from wav? Typically it should be the opposite (mp3 has a time delay compared to wav). For example it is so after converting wav to mp3 using sox, and checking the waveforms for the files in both Audacity and Essentia.

![timeshift_sox](https://cloud.githubusercontent.com/assets/409668/7026277/14e93920-dd49-11e4-9fd3-2383aada85cd.png)

**Comment by sertansenturk** [comment]
You are right about tihs problem being generic. I have tried with another set of mp3's in the CompMusic makam corpus and got different behaviors.

The mp3's were generated by ripping from CD's by different people with different configurations. Hence it is a problem of mp3 encoders/decoders being used in the process. 

There is no way to fix this generic problem except working with .wav format to get consistent results across all applications/platforms etc... Therefore I am closing this issue.
