### ISSUE TITLE
avlib too old on ubuntu 14.04

### ISSUE THREAD

**Issue by jcpeterson** [MTG/essentia#295]
I'm having trouble building essentia on ubuntu 14.04. To be clear, I can build fine, but not with all of the features I want (all ffmpeg related stuff like AudioLoader...etc). Part of the avlib requirements aren't met, and I can't update them.

Everything looks ok after running the configuration before building, except libswresample and libavcodec. I read in the last issue that libswresample is only an alternative so I'm not worrying about it, however, a missing libavcodec means I can't read in audio files with essentia (or so I believe at this point). I have libavcodec on my system, and essentia can see the pkg-config file, but the version that comes with ubuntu 14.04 is too old (<55), which is reported upon configuring with waf. I have verified this in the build log file.  

I've tried to update this but ubuntu won't let me since only version for trusty is old. I've tried adding a 3rd party ppa to get a new avlib or ffmpeg, and while they install, essentia still sees my old copies and I can't find any .pc files with the new installations so I don't know how to link them up. I also tried building ffmpeg from source but it's just a bunch of binary files and no libraries. 

On the essentia website, it says that some other library is the right version on 14.04, and that the avlib stuff is the correct version on 14.10. What does this mean? How is it helpful that essentia needs libraries that come with different versions of ubuntu? It looks like someone got essentia working on 14.10 on some blog, but I haven't seen any examples of 2.1 running on ubuntu 14.04. Is it possible to build essentia with avlib stuff on ubuntu 14.04? If so, please help, I can't figure out how on earth to update avlib stuff.

**Comment by dbogdanov** [comment]
Master branch requires at least libavcodec55 which is provided in Libav 10
2.1beta2 requires at least libavcodec53 which is provided in Libav 9

- Ubuntu Trusty (14.04) contains libavcodec54 (Libav 9)
- Ubuntu Utopic (14.10) contains libavcodec56 (Libav 11)

You should be fine installing [2.1beta2 version on 14.04](https://github.com/MTG/essentia/releases/tag/v2.1_beta2). Or you can install the required ```libav*-dev``` packages from Utopic [without upgrading all your system](http://unix.stackexchange.com/questions/170079/update-single-package-from-ubuntu-utopic-unicorn-when-running-trusty-tahr) in order to make use of the master branch.
