### ISSUE TITLE
not finding actual directory of libessentia.so

### ISSUE THREAD

**Issue by ErnestoAcc** [MTG/essentia#314]
I am new in linux, python and essentia. Using debian jessy

When I call (in python) import essentia:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: libessentia.so: cannot open shared object file: No such file or directory

(I see the file in /usr/local/lib/)

**Comment by ErnestoAcc** [comment]
i'm using Debbian branch release

**Comment by dbogdanov** [comment]
Use master branch. Did you run waf install after you've configure essentia to build with python?

**Comment by ErnestoAcc** [comment]
Yes I did. I've now uninstalled Debbian branch. 2.1.beta2-release or directly the master branch?

**Comment by dbogdanov** [comment]
Just use master branch.

**Comment by tarikki** [comment]
I ran into the same issue. Using the master branch and Ubuntu 14.04 LTS.

**Comment by dbogdanov** [comment]
@tarikki Can you attach your configuration log (```build/config.log```)?

**Comment by tarikki** [comment]
Thanks for pointing me to the `build/config.log`. It turned out that the correct version of `libavcodec` and `libavresample` were missing, but I think this is a common problem with Ubuntu 14 LTS because it doesn't have ffmpeg and the latest library `libavcodec` you can get for it is 54. I used the common workaround of installing ffmpeg from here https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media and then adding the pkg_configs from ffmpeg to my path. 

Now the configuration looks good, but the build terminates with the error message `/usr/bin/ld: /opt/ffmpeg/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC /opt/ffmpeg/lib/libavformat.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status`. 

It seems that ffmpeg is back in ubuntu 15.04, so maybe the easiest way is to upgrade to a non-LTS release to be able to use essentia properly?

Here's the config log for what it's worth. 

[config.log.txt](https://github.com/MTG/essentia/files/41842/config.log.txt)

**Comment by trig-ger** [comment]
The error with -fPIC was fixed for me after changing ld.gold to ld.bfd in /usr/bin/ld symlink.

**Comment by urinieto** [comment]
Same problem here, couldn't find a workaround...

**Comment by urinieto** [comment]
Ok, everything works if I use the 2.0.1 branch (I was using the master branch before). I'm on Ubuntu 15.10.

**Comment by dbogdanov** [comment]
Can't reproduce this problem on a fresh install of Ubuntu 15.10 following installation instructions.

**Comment by georgid** [comment]
I got that working on UBUNTU 15.04 by running 
`sudo apt-get install -y build-essential libyaml-dev libfftw3-dev        libavcodec-dev libavformat-dev libavutil-dev libavresample-dev        python-dev libsamplerate0-dev libtag1-dev python-numpy-dev git` which I copied from the [dockerfile for Ubuntu](https://github.com/MTG/essentia-docker)

**Comment by georgid** [comment]
I realized that if the correct version of `libavcodec` is missing, .waf is indeed linking the library _essentia.so in a wrong way:
```
ldd /usr/lib/python2.7/site-packages/essentia/_essentia.so
	linux-vdso.so.1 =>  (0x00007ffed2df2000)
	**libessentia.so => not found**
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fac3c10e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fac3be0c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fac3bbf6000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fac3b9da000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fac3b60d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fac3c6b5000)
```

In my case I have ffmpeg installed but it is not in a standard path e.g. its libraries are in `/opt/user1/ffmpeg/lib/libavcodec.so`

To fix that I believe we need to instruct waf to search in the path `/opt/user1/ffmpeg/lib/` as well. I could not find a parameter to waf to change the default search paths. 
I tried therefore adding that to the $PATH variable and making a dynamic link to libavcodec, but none of these filxed it.

**Comment by georgid** [comment]
I solved my problem using the PyPI wheel under Cent OS 7 refer to #777
