### ISSUE TITLE
Make number of bands in BarkBands configurable

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#346]
Make number of bands in **BarkBands** configurable by user, similarly to **MelBands** and **ERBBands**. Implement a formula to calculate central frequencies for filters and band widths based on their number (check the code of [rastamat](http://labrosa.ee.columbia.edu/matlab/rastamat/)).

**Comment by dbogdanov** [comment]
@pabloEntropia

**Comment by pabloEntropia** [comment]
I've been looking for a justification to implement configurable BarkBands. I haven't found any famous application using Barks without the default values apart from this rastamat code. However I found this [paper]( http://asa.scitation.org/doi/10.1121/1.399849 ) from 1990 claiming that

> For most of these applications, it would be more convenient to have the relation between z and f specified in the form of an equation instead of a table

referring to the Bark scale. The paper is quite cited, so I don't know if is really useful but at least it should make sense to implement it in a configurable way.

**Comment by dbogdanov** [comment]
Adding @perfe to conversation for more feedback. How useful it would be to have a configurable bark scale?

**Comment by perfe** [comment]
I cannot give you references using nonstandard bark bands except two of my own where, to improve classification of drum sounds we split the 2 lowest bands in 2 halves each. I think the same reasons that apply to ERB could be applied here (if any). IMHO, the bandwidth and center could be dynamically moved whenever some "physiological" or "perceptual" realism is looked for (as we, as listeners are able to do that in order to improve the SNR of the signals we want to attend to). But I cannot give you papers doing that. Whenever a nonstandard Bark filtering is used, it is clear that the term Bark bands should not be used or be clearly explained.

**Comment by perfe** [comment]
These are the papers I mentioned before:
http://mtg.upf.edu/node/312
http://mtg.upf.edu/node/279

**Comment by pabloEntropia** [comment]
Thank you a lot @perfe . So maybe the best option would be to leave **BarkBands** as they are in order to be precise with the meaning and create **ParametricBarkBands** to be consistent with the rest of bands algorithms? This function would also be more suitable for further parameters as, for instance, splitting the first band like Perfe said.

**Comment by perfe** [comment]
Good idea! Keep BarkBands as "standard" and give the other one to break it!

**Comment by dbogdanov** [comment]
Our **BarkBands** are not standard anyways, as the first band is already split in two. Let's freeze this issue for a while to consider it later, and work on other priorities first (aka ConstantQ)

**Comment by carthach** [comment]
Resurrecting this old thread:

I actually went ahead and implemented this as TriangularBarkBands

I needed a BFCC extractor and since there are no standard implementations I decided to model the one in Rastamat (http://www.ee.columbia.edu/ln/rosa/matlab/rastamat/).

This required a customisable TriangularBarkBands algo to get the values identical to Rastamat. 

Anyway the pull request:
https://github.com/MTG/essentia/pull/621

**Comment by dbogdanov** [comment]
Great!
