### ISSUE TITLE
Cannot find gaia headers during waf compilation

### ISSUE THREAD

**Issue by aagnone3** [MTG/essentia#427]
Configuring waf finds the gaia library, since I set my PKG_CONFIG_PATH env variable to /usr/lib/gaia2/lib/pkgconfigpath (where gaia2.pc is located), but the ./waf compilation command fails, due to being unable to find gaia2/transformation.h.

I have attached all output for both the following commands:

./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia > configure_results.txt 2>&1

./waf > waf_results.txt 2>&1

[configure_results.txt](https://github.com/MTG/essentia/files/321908/configure_results.txt)
[waf_results.txt](https://github.com/MTG/essentia/files/321907/waf_results.txt)

**Comment by aagnone3** [comment]
Likely also useful
(build/config.log renamed to .txt)
[config.txt](https://github.com/MTG/essentia/files/321922/config.txt)

**Comment by alastair** [comment]
How did you install gaia? From your config.txt it looks like it has found it in `/usr/local`:
```
Checking for 'gaia2'
['/usr/bin/pkg-config', '--cflags', '--libs', '--modversion', 'gaia2']
out: -I/usr/local/include -I/usr/include/qt4 -I/usr/include/qt4/QtCore -L/usr/local/lib -L\[QtCore\] -lgaia2 -lQtCore -lyaml
```
but you say that you have items in `/usr/lib/gaia2/lib/`
Did you configure gaia with a different prefix? If you did, then there may be a bug in gaia that we need to fix.

can you give the output of `ls -lR /usr/lib/gaia2`?

Otherwise, if you don't actually need gaia, you can skip `--with-gaia` in the configure line
