### ISSUE TITLE
Freesound extractor stores statistics to yaml while frames to json

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#434]
Statistics information should be stored to json for consistency just as the frame-level information.

@ffont  Will this break the Freesound infrastructure? We have python script for conversion to yaml if necessary.

**Comment by ffont** [comment]
It would break it but fix is easy. Yaml files are only read when loading descriptors to gaia, so this is the only part that should be modified. After that these files are not really used.
I'd be happy to move to json so it si unified with frames descriptors.

**Comment by ffont** [comment]
In fact we use the load function from gaia (https://github.com/MTG/freesound/blob/master/similarity/gaia_wrapper.py#L190) so we might not even need to change this.

Just make sure that 'analysis.statistics.path' returns a path with .json instead of .yaml, modify similarity_update command (https://github.com/MTG/freesound/blob/b6793091c1cbec26a6a5f9b48b8e9a1a43b56ea7/general/management/commands/similarity_update.py) and also analysis code to move json file instead of yaml file (https://github.com/MTG/freesound/blob/master/utils/audioprocessing/essentia_analysis.py#L90)
