### ISSUE TITLE
add support for DCT type III in DCT algorithm

### ISSUE THREAD

**Issue by georgid** [MTG/essentia#507]
add 
- parameter to select DCT type III (used by htk) or DCT type II (use in Slaney's). Currently in essentia we have type II . Note that in librosa they use type III by default.
-   paramter for optional liftering after DCT. 
Liftering is explained in equation 5.12 in the [htkbook](http://www.dsic.upv.es/docs/posgrado/20/RES/materialesDocentes/alejandroViewgraphs/htkbook.pdf). In short, liftering  rescales the cepstral coefficients c_n to have similar magnitudes for pragmatic reasons.
It can be reimplmented from matlab from [here](http://www.ee.columbia.edu/~dpwe/resources/matlab/rastamat/lifter.m) in the [toolbox](http://www.ee.columbia.edu/~dpwe/resources/matlab/rastamat/)
We should add a parameter `lifteringBands` parameter, that sepcifies the number of liftering bands. If it is 0 (default), no liftering will be performed.

**Comment by georgid** [comment]
@pabloEntropia 
[MFCCs_old.zip](https://github.com/MTG/essentia/files/591775/MFCCs_old.zip)
A reference implementation look at MFCCStanAlone->RobustAudioProcessor.cpp
function etractMFCC()

**Comment by georgid** [comment]
@pabloEntropia
To sum up: in the DCT algorithm there will be a new parameter dctType. 
In the MFCC algorithm there will be 3 new parameters:
- dctType = {2,3} default = 2
- logType  = {'natural','db' } default = 'db' 
- liftering  = {True, False} deafault = False
Deafault values will correspond to current implementation for backward compatibility.

**Comment by dbogdanov** [comment]
@georgid I've commended on logType in #510

**Comment by pabloEntropia** [comment]
@georgid I have changed the dct type III implementation in order to behave the same as Librosa as you proposed. However I realized that the formula becomes different from the Wikipedia formula (that is referenced inside the algorithm, https://en.wikipedia.org/wiki/Discrete_cosine_transform). If we just assume that Librosa is right I think it is ok, otherwise we should discuss it.

**Comment by georgid** [comment]
Yes, lets try to have the same DCT type III as in librosa  since it follows the Dan Ellis matlab implementation (see first comment), which is intact with htk.

**Comment by pabloEntropia** [comment]
I have created a 'liftering' parameter inside DCT that can be called from MFCC and a regression test for it. On my implementation, when 'liftering' is 0, it bypasses the liftering, and when it is a positive real it computes it in the HTK style. I have observed that the matlab code you proposed forces liftering factor to be an integer, do you think i should do the same? I don't see the point.
And second, should I create a parameter 'inverseLiftering' or it is not useful?

**Comment by georgid** [comment]
> when it is positive real it computes it in the HTK style.
Liftering rescales by a weight in a sine function, given in equation 5.12 in htk book (see above), so it should be an integer. Yes, we would like to have inverse liftering, but lets  do it in issue #487.

**Comment by dbogdanov** [comment]
Can merge this too if it is ready...

**Comment by pabloEntropia** [comment]
I have been doing some test proposed by @georgid and results are not very close to HTK so I will need some extra time to debug it.

**Comment by dbogdanov** [comment]
@pabloEntropia Try using Windowing with normalized=False.

**Comment by pabloEntropia** [comment]
Finally I have found the difference by looking in [HTK matlab implementation](https://es.mathworks.com/matlabcentral/fileexchange/32849-htk-mfcc-matlab) . Basically the differences are 2:

- HTK multiplies the audio signal by 2¹⁵ to explode the range of 16 bit shorts. 
- Scaling factor for the energy coefficient is a bit different to the Librosa DCT implementation.
However they are still not the same but close enough I guess. You can see the shape of all the implementations in this [notebook](https://github.com/georgid/mfcc-htk-an-librosa/blob/master/MFCC-htk-with-liftering-real-case-Test.ipynb)
So should I use the matlab DCT formula instead of the Librosa's?

**Comment by pabloEntropia** [comment]
I think we can close this issue  @dbogdanov
