### ISSUE TITLE
Implement Chromaprint wrapper algorithm

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#517]
Follow Chromaprint [API](https://bitbucket.org/acoustid/chromaprint/src/master/src/chromaprint.h?fileviewer=file-view-default).

Algorithm inputs: 
- ```vector<StereoSample> audio```
- ```Real sampleRate```

Algorithm output: 
- ```std::string fingerprint```

Related to #474

Convert all values in input from Real to 16-bit int format to be able to use Chromaprint API.

**Comment by dbogdanov** [comment]
If possible, preferred input should be mono (```vector<Real>```) instead of stereo.

**Comment by pabloEntropia** [comment]
I have the wrapper working in Standard mode. There is a demostration retrieving the AcousticBrainz id from the audio in this [gist](https://gist.github.com/pabloEntropia/bd1582d3c90bcee3c16863e6e5efb68f).
I have noticed that the algorithm is able to retrieve the AB id by just fingerprinting fragments instead of the full length of the track ( I used 30s segments in my example). So probably for the streaming mode it would be better to write an algorithm that retrieves a fingerprint each `analysisSize` seconds so it doesn't depend on previous knowledge about the input.

**Comment by dbogdanov** [comment]
That looks good. Correct, for the streaming mode we want to analyze on segments, but it would be great to still have an option to analyze on a complete input (if the ```analysisSize is set to 0).

**Comment by dbogdanov** [comment]
I guess the computed fingerprint should be concatenable, that is fingerprint(segment1+segment2) = fingerprint(segment1) + fingerprint(segment2). You can check if it is so in the gist.

**Comment by pabloEntropia** [comment]
There is a problem with that because in order to call the chromaprint api you have to specify the number of samples that it has to analyze. Standard mode is implemented as you say but I don't think it is possible in Streaming mode unless you specify the duration previously as an optional parameter. 
I updated the [gist](https://gist.github.com/pabloEntropia/bd1582d3c90bcee3c16863e6e5efb68f) with your proposed experiment.
Results suggest that it is possible to concatenate finguerprints and retrieve the AcouisticID key as far you include the proper song duration in the query.

**Comment by marv1nnnnn** [comment]
any update on this？

**Comment by dbogdanov** [comment]
@marv1nnnnn It is implemented in #601. To be merged soon.
