### ISSUE TITLE
Descriptions of Vibrato

### ISSUE THREAD

**Issue by minzwon** [MTG/essentia#579]
1. Description on Output
vibratoFrequency (vector_real) - estimated vibrato frquency [Hz]; zero if no vibrato was detected.
vibratoExtend (vector_real) - estimated vibrato frquency [Hz]; zero if no vibrato was detected.

**vibratoExtend might be the vibrato in 'cents'.**

2. Default parameter setups
maxExtend (real ∈ (0, ∞), default = 250) :
maximum considered vibrato extend [cents]

maxFrequency (real ∈ (0, ∞), default = 8) :
maximum considered vibrato frequency [Hz]

minExtend (real ∈ (0, ∞), default = 50) :
minimum considered vibrato extend [cents]

minFrequency (real ∈ (0, ∞), default = 4) :
minimum considered vibrato frequency [Hz]

**I think default values should be swapped. Hz values should be larger than the cent values usually.**

**Comment by pabloEntropia** [comment]
Hi @minzwon !
I reviewed the code and it seems to be a documentation mistake.  **vibratoExtend** is the amplitude (or depth) of the vibrato in cents. The default **frequency** and **extend**  values have different ranges because they are the threshold for the vibrato rate in Hz and extend (or extent) in cents.
