### ISSUE TITLE
Number of MFCC coefficients in Python?

### ISSUE THREAD

**Issue by urinieto** [MTG/essentia#65]
I am trying to change the number of MFCC coefficients using the Python wrapper like this:

```
import essentia.standard as ES
bands, coeffs = ES.MFCC(spectrum, numberCoefficients=14)
```

However, I get the following error:

```
TypeError: __call__() got an unexpected keyword argument 'numberCoefficients'
```

In the [documentation](http://essentia.upf.edu/documentation/reference/std_MFCC.html) it says that the `numberCoefficients` parameter should be available. Am I doing something wrong?

**Comment by HaitongZhang** [comment]
I have also met a similar question, but which cannot be solved by specified initialization as:

BFCCS = BFCC(numbercoefficients=30)

since the error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() got an unexpected keyword argument 'numbercoefficients'
