### ISSUE TITLE
Add script for static builds of chromaprint library

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#719]
Currently, static builds of Essentia extractors are missing chromaprint dependency.

**Comment by eadward** [comment]
Hi, I was doing this actually. I created a new script to compile chromaprint statically, and then configured essentia with the --build-static-examples option (to build static version of the extractors to use in another machine). Unfortunately I get an error when compiling the examples:

> essentia-2.1beta3/packaging/debian_3rdparty/lib/libchromaprint.a(fft_lib_avfft.cpp.o): In function `chromaprint::FFTLib::FFTLib(unsigned long)':
fft_lib_avfft.cpp:(.text+0xdb): undefined reference to `av_rdft_init'
essentia-2.1beta3/packaging/debian_3rdparty/lib/libchromaprint.a(fft_lib_avfft.cpp.o): In function `chromaprint::FFTLib::~FFTLib()':
fft_lib_avfft.cpp:(.text+0xf9): undefined reference to `av_rdft_end'
essentia-2.1beta3/packaging/debian_3rdparty/lib/libchromaprint.a(fft_lib_avfft.cpp.o): In function `chromaprint::FFTLib::Compute(std::vector<double, std::allocator<double> >&)':
fft_lib_avfft.cpp:(.text+0x6b5): undefined reference to `av_rdft_calc'
collect2: error: ld returned 1 exit status

It is some sort of problem related to Chromaprint and FFMpeg, and eventually related to the way I compiled Chromaprint. Are there any options i should be aware of (or any other ideas)? thanks!

**Comment by dbogdanov** [comment]
Chromaprint depends on [FFMpeg](https://github.com/acoustid/chromaprint#fft-library) for the FFT computation, but you can also build it with a slower KissFFT, in which case no external dependency is necessary (the code for KissFFT is already included in libchromaprint).

**Comment by eadward** [comment]
Thanks. I used kissfft instead and it worked fine for both windows and linux. The only problem is that the vamp plugin for linux cannot be created due to a problem with kissfft. If you want I can report that here. BTW: do the vamp plugins also interface the example extractors? I intend to use them in NodeJS but not sure if they need to be created from scratch in JS using the vamp plugin. 

In the meantime I managed to create the static binaries of a new extractor that I created for both windows and linux which is great. There were a few issues on the way so I will report that somewhere in case it is useful for others.

Many thanks for the help!
