### ISSUE TITLE
ImpotError : No module named 'essentia'

### ISSUE THREAD

**Issue by 24320152202743** [MTG/essentia#724]
I followed the instructions at http://essentia.upf.edu/documentation/installing.html and I successfully compiled and installed it .But it doesn't work when I want to import it .Could anyone help?!

**Comment by czrcbl** [comment]
I am facing the same problem, I am trying to install essentia in a environment named venv, I have create It with `virtualenv` tool, not conda.
 
I used:
`./waf configure –build-static –with-python –python=/path_prefix/venv/bin/python –with-cpptests –with-examples –with-vamp --prefix /path_prefix/venv/
`
Where `path_prefix` is the path until my environment.

Then I run `python3 ./waf` as instructed, it was compiled with no errors. Finally I installed with `python3 ./waf install`.
I ran all the commands with my environment activated.

A folder named essentia with the c header files was created in `venv/include` and `libessentia.so` file was created in the `libs` folder, but there is no essentia folder on the venv/lib/python3.6/site-packages or anywhere else inside the environment.

**Comment by czrcbl** [comment]
I went though the installation procedure again, but using an environment with python 2, and now it works. I may have done something wrong, or maybe there is a problem with python 3 installation.

**Comment by sildeag** [comment]
The likely cause of your `import` error is that with `python3` I have found that the module `_essentia.so` used in the `python` interface referred to in issue #743 is created with a different name ie. `_essentia.cpython-36m-x86_64-linux-gnu.so`.  Your name may be different but the principle is the same.  Solved with  `ctx.env['pyext_PATTERN'] = "%s.so" and `wscript` code to alter the ctx.env['PYTHONDIR'] for the `python3` `essentia` package location.    I am hoping this issue is fixed as it would eliminate a potential "conflict" for my pull request.

**Comment by 24320152202743** [comment]
Finally I figured out. using python3 to compiled and install will create a folder in python3/dist-package which is not the interpreter environment I use .It should be moved to somewhere like python3.5/dist-package it depends on your chose.And using 
python
>>>import sys
>>>sys.path

to check your python path

**Comment by dbogdanov** [comment]
You can use ```--pythondir``` flag in ```waf configure``` to specify the desired installation path ([more details here](https://github.com/MTG/essentia/pull/774#issuecomment-417312701)).
