### ISSUE TITLE
How to consume the output of an algorithm in real-time?

### ISSUE THREAD

**Issue by evyncke** [MTG/essentia#75]
Essentia appears to be quite powerful when the 'last' algorithm is to pool/process statistics and/or save date to files.

I wonder whether it is also suitable for a real-time processing of audio:
- I was able to feed it with live audio through a named pipe and AudioLoader :-)
- but I am afraid that if I want to process real-time with my own code (for example taking the output of Spectrum) then I MUST implement a Sink or a full Algorithm.

Implementing Algorithm => but how can I register it? I have built a simple one but cannot create it => 'not registered'.

Implementing Sink => neither documentation nor example exist

The auto vectorInput does not appears to be able to receive data from Spectrum and there is no real way to synchronize the processing. Starting a specific thread for this purpose appears like an overkill.

Any help on Sink and Algorithm will be welcome :-)

**Comment by borg** [comment]
Would you care to share some code on the real time processing as I haven't found any compiling  examples on the best approach. A named pipe and audio loader? How are you continuously updating and processing this? I found one example using a RingBuffer for what seemed this purpose, but haven't had enough time to figure out the right setup.

**Comment by evyncke** [comment]
It has been a long time since then... But, yes named pipe was used

-éric

From:  Andreas Borg <notifications@github.com>
Reply-To:  MTG/essentia
<reply+0045bd1f04af2a8f9df189b0f5eb5efb7e95479a0c7c12a092cf00000001110fb5a39
2a169ce01cd537e@reply.github.com>
Date:  jeudi 5 mars 2015 07:11
To:  MTG/essentia <essentia@noreply.github.com>
Cc:  Eric Vyncke <eric@vyncke.org>
Subject:  Re: [essentia] How to consume the output of an algorithm in
real-time? (#75)

**Comment by borg** [comment]
Right, I know what it's like. 
I don't find any examples showing real time analysis, and I do realize only a subset of the algorithms would apply in that scenario. If you got it running smoothly, any code snippet for setup, process and buffer clearing would be great. Otherwise, it's great to know it's even possible.

Thanks for your reply

**Comment by AnaTP** [comment]
Hello everyone, I'm also interested in real time analysis, and I can't find a way to do it. @borg did you got it done? 

Can you help me?

Thanks in advance

**Comment by borg** [comment]
I was using it in an openFrameworks context (using this [fork](https://github.com/prisonerjohn/openFrameworks/tree/feature-64bit) ) and got non-realtime working. Due to lack of documentation / examples on realtime analysis I ended up rolling my own realtime [addon](https://github.com/borg/ofxGist) instead. I think it is possible though.

**Comment by dbogdanov** [comment]
For real-time you can use RingBufferInput as an input for you streaming network of algorithms and run it on every audio frame. See an example here:
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/EssentiaOnset.cpp#L63
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/EssentiaOnset.cpp#L112
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/main.cpp#L74

**Comment by schramm** [comment]
Hi. Is there any updated example for real-time  processing in Essentia?
