### ISSUE TITLE
Using SBic

### ISSUE THREAD

**Issue by smeben** [MTG/essentia#970]
I am trying to find resources on using the segmentation. I can't figure it out. I am using python streaming. What do I need to pass in to SBic and how do I generate it. I passing in mfcc but it isn't a matrix_real.

**Comment by smeben** [comment]
Bump

**Comment by pabloEntropia** [comment]
You need to accumulate `MFCC` vectors to create the `matrix_real` required by `SBic`.
In streaming mode, the code to get the "MFCC-gram" looks something like this:
``` Python
# Code extracted from our streaming tutorial

import essentia
from essentia.streaming import *

filename = 'your_audio'

loader = MonoLoader(filename=filename)
frameCutter = FrameCutter(frameSize=1024, hopSize=512)
w = Windowing(type='hann')
spec = Spectrum()
mfcc = MFCC()
pool = essentia.Pool()

loader.audio >> frameCutter.signal
frameCutter.frame >> w.frame >> spec.frame
spec.spectrum >> mfcc.spectrum
mfcc.bands >> None
mfcc.mfcc >> (pool, 'lowlevel.mfcc')

essentia.run(loader)
```

Now we can use the data in the pool to feed `SBIc`. This is easy to achieve in standard mode:
``` Python
import essentia.standard as es
segmenter = es.SBic()
segments = segmenter(pool['lowlevel.mfcc'])
```

**Comment by smeben** [comment]
Thank you for the response. Two follow ups to this. How can I use the streaming version of sbic? I can’t hook the output off mfcc to sbic due to a type mismatch, and I don’t know if there is a way to hook a pool to an input, it says it is not a stream connector. Also the result I am getting from sbic seems to be inaccurate. I ran the same file through SonicVisualizer to compare the sbic output.

**Comment by pabloEntropia** [comment]
In streaming mode, `SBic` can only be connected to algorithms sourcing `vector_vector_real` outputs so it is not possible to connect  `MFCC` or `Pool` to it. I would recommend to use `SBic` in standard mode after the feature extraction step.
Regarding the comparison to SonicVisualizer, the decision on the locations of the segments depends on the input features. Given that the features used by SonicVisualizer are probably not Essentia `MFCC`, the output segments are not supposed to be in the same positions.
If you want to improve the segment positions, I would suggest combining timbral (e.g., [MFCC](https://essentia.upf.edu/reference/std_MFCC.html)), tonal (e.g., [HPCP](https://essentia.upf.edu/reference/std_HPCP.html)), and rhythmic (e.g., [RhythmTransform](https://essentia.upf.edu/reference/std_RhythmTransform.html)) features. You can extract them in the same way as in the `MFCC` example above, and then use NumPy functions to stack them before feeding them to `SBic` in standard mode.

**Comment by smeben** [comment]
I am trying to use the NumPy stack, but it looks like MFCC is coming back with 13 entries and HPCP is returning 12, so the array shapes don't match and NumPy cant stack them

**Comment by smeben** [comment]
ok i think i might have figured part of this out, which is stacking only the 2nd dimension of the returned features since those all match. however sbic is still returning results that feel like they are very wrong. it is giving me segments that are only a couple of seconds long (some less than a second)
`timbral_features = copy.deepcopy(pool['mfcc.mfcc'].transpose())
tonal_features = copy.deepcopy(pool['tonal.hpcp'].transpose())
rhythmic_features = copy.deepcopy(pool['mel.bands'].transpose())
features = numpy.stack((timbral_features[1], tonal_features[1], rhythmic_features[1]))
segmenter = essentia.standard.SBic()
segments = segmenter(features)`

**Comment by pabloEntropia** [comment]
Nice that you have found a working solution! However, I'd like to clarify what's going on.
Firstly, you couldn't stack the features because you were trying to do it along the feature axis instead of the time axis. For example:
``` Python
print('MFCC shape {}'.format(pool['lowlevel.mfcc'].shape))
print('HPCP shape {}'.format(pool['lowlevel.hpcp'].shape))
```
Outputs:
```
MFCC shape (37543, 13) <-- (timestamps, feats)
HPCP shape (37543, 12) <-- (timestamps, feats)
```
It shows that the arrays have the length for the first (time) axis but a different one for the second (feature) one.

After this, you managed to stack them because you selected just the second dimension (`[1]`) of each feature vector, but this is far from an ideal solution as you are discarding most of the information contained in the rest of dimensions.  Finally, you are presenting the data in a wrong shape to [SBic](https://essentia.upf.edu/reference/std_SBic.html) because of the transpositions. SBic expects the data to be arranged as `[timestamps, features]`, to achieve you should re-transpose the features. From your code,
``` Python
segments = segmenter(features.transpose())
```

Or even better, do it in one line leveraging all the feature dimensions with `hstack`:
``` Python
feats = np.hstack([pool['lowlevel.mfcc'], pool['lowlevel.hpcp']])

print('Stacked features shape {}'.format(feats.shape))
```
Outputs:
```
Stacked features shape (37543, 25)
```

I'm closing this issue now as the original question has already been answered.

Good luck!
