### ISSUE TITLE
Static build fails on linking build/src/examples/essentia_standard_beatsmarker

### ISSUE THREAD

**Issue by MeijisIrlnd** [MTG/essentia#976]
Hi, trying to build this statically, the ./waf command fails on this step, have attached a screenshot of the error, if you'd prefer me to paste it I can do, any ideas? 
![Screen Shot 2020-04-25 at 17 41 01](https://user-images.githubusercontent.com/38221014/80285366-5437d280-871c-11ea-808f-7adc25222063.png)

**Comment by dbogdanov** [comment]
Use `packaging/build_3rdparty_static_debian.sh` script for building static dependencies. 

This issue with linking to zlib is due to the fact that [a proper link flag is missing from the pkgconfig file](https://github.com/taglib/taglib/issues/872) (`taglib.pc`) of your version of taglib. This is why we [patched it in our build script](https://github.com/MTG/essentia/blob/master/packaging/debian_3rdparty/build_taglib.sh#L22).

Taglib has fixed the issue since then, and it should all work fine in their next release. We'll update accordingly.
